Make the Portal Editor compile on the Admin Server which is Ubuntu 14.04 with libssl-dev v1.0. The arsd/http2 module relies on libssl-dev v1.1 so you get errors like: undefined reference to OPENSSL_init_ssl. Adding a compilation flag to link against ssl v1.0.